### PR TITLE
Implemented initial handshake to S3

### PR DESCRIPTION
**Pull request by selenaxiao-nist**
Implemented initial handshake to S3 (copy an empty file)
Handshake action is run when "account-implemented" label is added to account request

### CODE REVIEW

**Review by JustKuzya — APPROVED** [review]
Nice work! I especially liked the README.MDs in the direct ories to remind us what the directories were made for. 👍

**Review by JustKuzya — APPROVED** [review]
The change-set looks OK

**Comment by selenaxiao-nist** [comment]
Changes:

- Once a create user account request is approved (ACCOUNT_APPROVED label), automatically parse submitted user information to create a user YAML file
- Instead of empty file as handshake, send a YAML file with information on how to get to user YAML file, for AWS infrastructure to use for automatic user creation

**Review by JustKuzya — APPROVED** [review]
The code changes look reasonable, though the SSP.xml has some conflicts with the upstream - please review or pull in the upstream changes.

Though, I have food for thought:
Ubuntu LTS usually has a 5-years support cycle. Hence, using Ubuntu 20.04 for GitHub runners means that we would need to upgrade to Ubuntu 22.04 or 24.04 before Apr 2025.

**Comment by selenaxiao-nist** [comment]
I pulled in the upstream for the SSP xml. The branch can be merged without conflicts, but it can't be rebased (unspecified conflicts)

**Review by iMichaela — APPROVED** [review]
everything was reviewed . LGTM

**Pull request merged**
